### ISSUE TITLE
komorebi: lock screen button conflict

### ISSUE THREAD

**Issue by lizhuoran1019** [aik2mlj/config-win#1]
Win+L in komoberi conflicts with win11 lock screen shortcuts.
Can you tell me how you handle it?

**Comment by aik2mlj** [comment]
Hi! Thanks for your interest. I changed the windows registry since I don't need the kindbinding for locking my laptop. You can google how to change registries and customize it to your liking.
I have switched to Linux for almost half a year, so my config might be outdated. Please keep that in mind ;)

**Comment by lizhuoran1019** [comment]
Thank you for your reply！I will try it later.
